apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=8901e3af3b83f599b89562162cdb2854f57082d3 # tag=v1.3.0-rc.1

patchesStrategicMerge:
- spawner_ui_config.yaml
- logos-configmap.yaml

images:
- name: quay.io/ibm/kubeflow-jupyter-web-app-ppc64le
  newName: quay.io/ibm/kubeflow-jupyter-web-app-ppc64le
  newTag: v1.3.0-rc.1
