apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/gajanankulkarni-18/kubeflow/components/notebook-controller/config/overlays/kubeflow?ref=dccd14f4eea6fb1308bc47d9508c4cd8cc1d714a # tag=v1.3.0PPC
  #- github.com/kubeflow/kubeflow/components/notebook-controller/config/overlays/kubeflow?ref=8901e3af3b83f599b89562162cdb2854f57082d3 # tag=v1.3.0-rc.1

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.3.0-rc.1
