apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-authservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gajanankulkarni-8/argoflow
    targetRevision: PPC
    path: kubeflow/common/oidc-authservice
    kustomize:
      version: v4.4.1
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
