apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gajanankulkarni-8/argoflow
    targetRevision: PPC
    path: kubeflow/notebooks/tensorboards-web-app
    kustomize:
      version: v4.4.1
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
