apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoflow/argoflow
    targetRevision: HEAD
    path: kubeflow/notebooks/tensorboard-controller
    kustomize:
      version: v4.4.1
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
