apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/gajanankulkarni-18/mpi-operator/manifests/overlays/kubeflow?ref=3043919b1531e03050f8d76b708083af7f950012

images:
- name: qwerty1802/mpi-operator
  newName: qwerty1802/mpi-operator
  newTag: latest
  # digest: sha256:deafaee4d16c8983565b18cd20a3c786b92aa1be15cd0f3d74b5d9226d5e0792
