apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/mpi-operator/manifests/overlays/kubeflow?ref=424088cef4358e1c8566677704924ddab657e8e8

images:
- name: qwerty1802/mpi-operator
  newName: qwerty1802/mpi-operator
  newTag: latest
  # digest: sha256:deafaee4d16c8983565b18cd20a3c786b92aa1be15cd0f3d74b5d9226d5e0792
