apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "W1ozz6ac2H1IX7Fho1PfMxclzYwSFHjgbkYSPc63s/M2+floo2q2gyycepxtquUA\nJQ96nrUa5aPbXia2MflGYN5pIzKWH8xWSkUoTt6QNqAJxWCBbsjfD+lVLk0MxoBd\n5iWxqDDk3RM8mJsvQMhXxcflFEpaD3yf5ViwUgIoViA="
