apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "Xr0YE4P3ei/YdG7kL0fHMeQvpqz+0xDKYIaaUUIqmC8il6yf0dNSQa0DfSUw5nl9\n9QSnPMvtOI+RYjQys4BGVcCyz5fM+fEEUypXgaW9fqxRe8CM9M3GmND4aAIwx9nS\naysSoee56uifqGP7SKgyyskOhwfy8cshw6xwOWlMIlU="
