apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "WAoZXWZfixGmscdROtvU2qBkiG3pzmGVXCViP5by9fYPJgwCs9ZrGm5rWyf6mKK3\nFY0AMaR9+lhQBzZkrPbE+lw8Wxhq4dTwbUXIlq1Gxr6vud+X97gbNNB5b6+Z2Ct3\nICBlIx7WRFY8e/qGQW2xBrH5FOMQZgLI3gmDplDzWYI="
