apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "hSg6E5cNKKGwg5ZlKFYMA1pANbYB3HTMsqwD0OyRZgekM4loFrq5mmzdHP+aK5bU\n4kdmUWu5ujrNtihozFlTLJr4UPafWn/ha7eooI0cbPIJEushVe5nfcNkUp4owy6Y\nfGfYG641v98aH6P9O2FMRHr+PEcsFY+SBhoNMHCh74Y="
